services:
  app:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344321
      POSTGRES_DB: fuel_flow
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
