"""add_favourites_table

Revision ID: c68cf9d55ad4
Revises: 522bf22f85d7
Create Date: 2026-06-03 10:40:06.590588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c68cf9d55ad4"
down_revision: Union[str, Sequence[str], None] = "522bf22f85d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "station_id", name="uq_user_station"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favourites")
    # ### end Alembic commands ###
