"""add price_history table

Revision ID: 36d3066bb7a2
Revises: 62eecbb19cbc
Create Date: 2026-07-01 08:47:02.428160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "36d3066bb7a2"
down_revision: Union[str, Sequence[str], None] = "62eecbb19cbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_histories",
        sa.Column("station_id", sa.String(length=36), nullable=False),
        sa.Column(
            "fuel_type", sa.Enum("diesel", "e5", "e10", name="fueltype"), nullable=False
        ),
        sa.Column("price", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_history_station_recorded",
        "price_histories",
        ["station_id", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_history_station_recorded", table_name="price_histories")
    op.drop_table("price_histories")
    # ### end Alembic commands ###
